### ISSUE TITLE
Potential Code improvement and question about one line of code.

### ISSUE THREAD

**Issue by frankgu** [tencentyun/cos-js-sdk-v5#16]
https://github.com/tencentyun/cos-js-sdk-v5/blob/481fd91187fcbf3c0d23a3ec76643fdfb1a63147/server/sts-auth.js#L176-L186

# 1. Potential improvement
## Supporting reference
- [Reference link](https://stackoverflow.com/a/41507712)
> Node 6 and above now includes ES6 default parameters

## Changes
1. Initialize the parameters with the default parameters technique
2. Also I found that in the following code, you haven't update/change the `query` and `headers` parameters, so I move them the parameters of this function.

## Final version of the code block
```
function getAuthorization (keys, method='GET', pathname='/', query={}, headers={}) {
     var SecretId = keys.credentials.tmpSecretId; 
     var SecretKey = keys.credentials.tmpSecretKey; 
 
     pathname.indexOf('/') === -1 && (pathname = '/' + pathname); 
} 
```

# 2. Question about one line
`pathname.indexOf('/') === -1 && (pathname = '/' + pathname);`
I've tested the function withouth this line, it seems that this line is useless. I think it should be safe to remove this line.

# 3. General advices
- use `let` or `const` instead of `var` [Reference link](https://wesbos.com/javascript-scoping/)
- use `async .. await` instead of `promise` [Reference link](https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9)

**Comment by carsonxu** [comment]
Thanks for suggestions.
1. This will not change because it will run error when old version projects just update the sdk version.
2. Someone maybe get errors if they use `pathname:'1.txt'` without an '/' prefix.
3. I hope it's compatible on different browser without babel and it works when somebody copy some code into their project. So code style of this project won't exceed ES5 specification.
